/**
 * Using only the GraphQL endpoint, we don't need this atm. But lets keep it for consistency (as it was auto-generated by NestJS CLI) and hypothetical future requests
 */

import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }
}
